import {
  defaultCupboardForm,
  defaultFoodForm,
  defaultIngredientForm,
  defaultRecipeForm,
  defaultShoppingListForm,
  defaultShoppingListItemForm,
} from "./constants.js";

export const state = {
  route: "dashboard",
  error: "",
  loading: false,
  currentUser: null,
  authSubject: "",
  foodEntries: [],
  ingredients: [],
  recipes: [],
  recipesMeta: { total: 0, limit: 25, offset: 0 },
  cupboardItems: [],
  cupboardLoading: false,
  cupboardLoaded: false,
  cupboardSubmitting: false,
  cupboardError: "",
  cupboardSuccess: "",
  foodForm: defaultFoodForm(),
  cupboardForm: defaultCupboardForm(),
  ingredientForm: defaultIngredientForm(),
  recipeForm: defaultRecipeForm(),
  ingredientDetailForm: null,
  recipeDetailForm: null,
  selectedIngredientId: "",
  selectedRecipeId: "",
  selectedIngredient: null,
  selectedRecipe: null,
  shoppingLists: [],
  selectedShoppingListId: "",
  selectedShoppingList: null,
  shoppingListForm: defaultShoppingListForm(),
  shoppingListDetailForm: null,
  shoppingListItems: [],
  shoppingListItemForm: defaultShoppingListItemForm(),
  shoppingListEditingItemId: "",
  shoppingListLoading: false,
  shoppingListError: "",
  shoppingListSuccess: "",
  authForm: {
    email: "",
    password: "",
  },
  cupboardEditingId: "",
  cupboardQuery: "",
  cupboardSort: "shelf",
  feedback: { type: "", message: "" },
  health: null,
};